vim.keymap.set("n", "<leader>G", vim.cmd.Git)
vim.keymap.set('n', '<Leader>gs', ':Git status<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>gl', ':Git log<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>gb', ':Git branch<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>gba', ':Git branch -a<CR>', { noremap = true, silent = true })
